openapi: 3.0.1
info:
  title: Classifier
  version: 1.0.0
servers:
  - url: http://localhost:5500
paths:
  /evaluate:
    post:
      summary: Evaluate a classifier
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: 'components.yaml#/components/schemas/ClassifierInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/ClassifierOutput'
