
# Test endpoints for the classifier. Values are hardcoded for testing purposes from one training examples.

### POST request to evaluate classifier
POST http://localhost:5500/classify
Content-Type: application/json

{
  "age": 40,
  "height": 180,
  "weight": 60,
  "gender": "MALE",
  "lifestyle": "SEDENTARY",
  "location": "EUROPE",
  "symptoms": [
    "Fever",
    "Difficulty Breathing"
  ],
  "cholesterolLevel": 120,
  "healthData": {
    "Temperature": 36.5,
    "BMI": 22.5,
    "Blood Pressure": 80
  }
}

### POST request to evaluate classifier
POST http://localhost:5500/classify
Content-Type: application/json

{
  "age": 50,
  "height": 180,
  "weight": 130,
  "gender": "MALE",
  "lifestyle": "SEDENTARY",
  "location": "EUROPE",
  "symptoms": [
    "Difficulty breathing",
    "Fatigue"
  ],
  "cholesterolLevel": 250.5,
  "healthData": {
    "Temperature": 36.6,
    "BMI": 24.7,
    "Blood Pressure": 180
  }
}