services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=healthdb
    volumes:  # Mount the volume to persist the data even after the container is removed.
      - postgres_data:/var/lib/postgresql/data
    networks:
      custom_network:
        ipv4_address: 192.168.1.100

  classifier:
    image: classification-service
    container_name: classifier
    ports:
      - 5500:5500
    volumes:
      - classifier_data:/app/data
    networks:
      custom_network:
        ipv4_address: 192.168.1.101

volumes:
  data: {}
  postgres_data: {}
  classifier_data: {}

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24  # Define a custom subnet
