package cvut.fel.virtualdoctor.model;

public enum DoctorType {
    GENERAL_PRACTITIONER,
    PEDIATRICIAN,
    DENTIST,
    ORTHOPEDIC,
    PSYCHIATRIST,
    OPHTHALMOLOGY,
    URGENT_CARE_CENTER,
    PHYSICAL_THERAPY,
    CHIROPRACTOR,
    ALLERGY_AND_IMMUNOLOGY,
    ENDOCRINOLOGY,
    RHEUMATOLOGY,
    GASTROENTEROLOGY,
    DERMATOLOGY,
    CARDIOLOGY,
    PULMONOLOGY,
    NEUROLOGY,
    ORL
}
