package cvut.fel.virtualdoctor.model;


public enum DoctorType {
    GENERAL_PRACTITIONER,
    PEDIATRICIAN,
    DENTIST,
    ORTHOPEDICS,
    PSYCHIATRIST,
    OPHTHALMOLOGY,
    URGENT_CARE_CENTER,
    PHYSICAL_THERAPY,
    CHIROPRACTOR,
    ALLERGY_AND_IMMUNOLOGY,
    ENDOCRINOLOGY,
    RHEUMATOLOGY,
    GASTROENTEROLOGY,
    DERMATOLOGY,
    CARDIOLOGY,
    PULMONOLOGY,
    NEUROLOGY,
    ORL, // Otolaryngology (Ear, Nose, and Throat)
    UROLOGY,
    HEPATOLOGY,
    ONCOLOGY,
    NEPHROLOGY
}
