openapi: 3.0.1
info:
  title: VirtualDoctor API
  description: VirtualDoctor API
  version: 1.0.0
paths:
  /api/evaluation/evaluate:
    $ref: './evaluator.yaml'
  /api/patient/new-patient:
    $ref: './patient.yaml'
  /api/disease/short:
    $ref: './disease_short.yaml'
  /api/disease/long:
    $ref: './disease_long.yaml'
